name: CICD using Jenkins and Maven
on: 
  push: 
  workflow_dispatch:
jobs:
  CICDjob:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repo on 
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build the source code
        run: mvn package

      - name: connect to LAB and deploy code on tomcat9
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: '3.110.141.146'
          user: 'labuser'
          pass: 'Nuvelabs123$'
          port: 22
          connect_timeout: 10s

          ## Giving the permission for copying the wat file to webapps directory
          first_ssh: |
             sudo chmod 777 /var/lib/tomcat9/webapps

          ## Move the war file to webapps directory
          scp: |
             './target/*war' => /var/lib/tomcat9/webapps

          ## Restart tomcat to automatically expand and deploy the application
          last_ssh: |
             sudo systemctl restart tomcat9


