name: CICD using Jenkins and Maven
on: 
  push: 
  workflow_dispatch:
jobs:
  CICDjob:
    runs-on: ubuntu-latest
    steps: 
      - name: clone the repo on 
        uses: actions/checkout@v4
      - name: Install Java and Maven on ubuntu server
        uses: actions/setup-java@v3
        with: 
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build the source code
        run: mvn package

